"""Extended material library: every vehicle system, not just the engine.

Typical handbook values (ASM Handbooks, MatWeb, EN/ISO/SAE standards and supplier datasheets) for one named
condition, each with a tolerance that reflects the spread between sources and suppliers. Where no reliable figure
exists a property is left out rather than guessed. Composites and polymers are anisotropic or temperature
sensitive; their values are for the stated layup or a dry, room-temperature condition.
"""

from __future__ import annotations

from autoeng.core.params import P, Param, Source

HANDBOOK = "Typical handbook value for this condition (ASM / MatWeb); verify against your supplier's certificate"
STD = "Minimum or typical value from the cited standard; actual parts usually exceed minimums"
SUPPLIER = "Typical supplier datasheet range for this class of product; compounds vary widely"

# Vehicle systems a material is used in (for filtering the library).
SYSTEMS: dict[str, str] = {
    "engine": "Engine",
    "turbo": "Turbo & induction",
    "exhaust": "Exhaust",
    "transmission": "Transmission & driveline",
    "brakes": "Brakes",
    "suspension": "Suspension & steering",
    "chassis": "Chassis & crash structure",
    "body": "Body panels",
    "wheels": "Wheels & tyres",
    "interior": "Interior & trim",
    "glazing": "Glazing & lighting",
    "fasteners": "Fasteners",
    "bearings": "Bearings",
    "seals": "Seals & hoses",
    "electrical": "Electrical",
}


def _p(value: float, tol: float, ref: str = HANDBOOK) -> Param:
    return P(value, Source.LITERATURE, tol, ref)


def _m(id, name, category, condition, uses, props, processes=(), notes=""):
    return {"id": id, "name": name, "category": category, "condition": condition, "uses": list(uses),
            "properties": {k: (_p(*v) if isinstance(v, tuple) else v) for k, v in props.items()},
            "processes": list(processes), "notes": notes}


STEEL = {"density": (7850, 20), "youngs_modulus": (205, 5), "poisson_ratio": (0.29, 0.01)}

EXTRA: list[dict] = [
    # ---------------------------------------------------------------- engineering steels
    _m("aisi_4340_qt", "AISI 4340 steel", "Steel", "Quenched & tempered (≈ 38 HRC)", ["engine", "transmission", "suspension"],
       {**STEEL, "yield_strength": (1080, 100), "ultimate_strength": (1240, 100),
        "fatigue_strength": (600, 80, HANDBOOK + "; unnotched, 1e7 cycles"), "thermal_conductivity": (44.5, 3),
        "specific_heat": (475, 15), "cte": (12.3, 0.5), "solidus_temp": (1427, 20)},
       ["forging", "CNC machining", "heat treatment"], "Crankshafts, connecting rods, axle shafts."),
    _m("aisi_4140_qt", "AISI 4140 steel", "Steel", "Quenched & tempered (≈ 30 HRC)", ["engine", "transmission", "suspension", "fasteners"],
       {**STEEL, "yield_strength": (850, 100), "ultimate_strength": (1000, 100), "thermal_conductivity": (42.6, 3),
        "specific_heat": (473, 15), "cte": (12.2, 0.5), "solidus_temp": (1416, 20)},
       ["forging", "CNC machining", "heat treatment", "nitriding"], "Shafts, hubs, steering knuckles, studs."),
    _m("aisi_8620_carburized", "AISI 8620 steel", "Steel", "Carburised & hardened (core values)", ["transmission"],
       {**STEEL, "yield_strength": (785, 100), "ultimate_strength": (1080, 120), "thermal_conductivity": (46.6, 3),
        "cte": (11.9, 0.5), "solidus_temp": (1420, 20)},
       ["forging", "gear cutting", "carburising", "grinding"],
       "Gear and pinion steel. Case hardness ~58-62 HRC; contact and bending fatigue depend on the case, not listed here."),
    _m("aisi_9310_carburized", "AISI 9310 steel", "Steel", "Carburised & hardened (core values)", ["transmission"],
       {**STEEL, "yield_strength": (1020, 100), "ultimate_strength": (1240, 100), "cte": (11.9, 0.5)},
       ["forging", "gear cutting", "carburising", "grinding"], "Premium gear steel (motorsport and aerospace gearboxes)."),
    _m("en_20mncr5_carburized", "20MnCr5 steel (EN 10084)", "Steel", "Case hardened (core values)", ["transmission"],
       {**STEEL, "yield_strength": (735, 80, STD), "ultimate_strength": (1080, 120, STD), "cte": (12.0, 0.5)},
       ["forging", "gear cutting", "carburising"], "The workhorse European transmission gear steel."),
    _m("en_18crnimo7_6_carburized", "18CrNiMo7-6 steel (EN 10084)", "Steel", "Case hardened (core values)", ["transmission"],
       {**STEEL, "yield_strength": (835, 80, STD), "ultimate_strength": (1180, 120, STD), "cte": (12.0, 0.5)},
       ["forging", "gear cutting", "carburising"], "High-load gears and final-drive pinions."),
    _m("aisi_52100_hardened", "AISI 52100 bearing steel", "Steel", "Through-hardened (≈ 62 HRC)", ["bearings", "transmission"],
       {"density": (7810, 20), "youngs_modulus": (210, 5), "poisson_ratio": (0.3, 0.01), "yield_strength": (2030, 150),
        "ultimate_strength": (2240, 150), "thermal_conductivity": (46.6, 4), "cte": (11.9, 0.5),
        "max_service_temp": (150, 20, HANDBOOK + "; above this, standard heat treatment loses dimensional stability")},
       ["forging", "grinding", "through hardening"], "Rolling-element bearings, CV-joint balls."),
    _m("sae_9254_spring", "SAE 9254 Si-Cr spring steel", "Steel", "Oil tempered wire", ["suspension", "engine"],
       {"density": (7850, 20), "youngs_modulus": (206, 4), "yield_strength": (1700, 100), "ultimate_strength": (1900, 100)},
       ["wire drawing", "coiling", "shot peening"], "Coil springs and valve springs."),
    _m("en_51crv4_spring", "51CrV4 spring steel", "Steel", "Quenched & tempered", ["suspension"],
       {**STEEL, "yield_strength": (1300, 150), "ultimate_strength": (1500, 150), "cte": (12.0, 0.5)},
       ["hot forming", "heat treatment", "shot peening"], "Leaf springs, anti-roll bars, torsion bars."),
    _m("aisi_300m_qt", "300M steel", "Steel", "Quenched & tempered (≈ 53 HRC)", ["transmission", "suspension"],
       {"density": (7830, 20), "youngs_modulus": (205, 5), "yield_strength": (1590, 80), "ultimate_strength": (1930, 70)},
       ["forging", "CNC machining", "heat treatment"], "Ultra-high-strength axle and half-shafts in motorsport."),
    _m("maraging_300_aged", "Maraging steel 300", "Steel", "Aged", ["transmission", "engine"],
       {"density": (8000, 20), "youngs_modulus": (190, 5), "yield_strength": (2000, 70), "ultimate_strength": (2050, 70),
        "thermal_conductivity": (25.5, 2), "cte": (10.1, 0.5)},
       ["CNC machining", "ageing"], "Racing gearbox shafts and valve-train parts."),
    _m("bolt_class_10_9", "Alloy steel bolt, property class 10.9", "Steel", "ISO 898-1", ["fasteners"],
       {**STEEL, "yield_strength": (940, 20, STD), "ultimate_strength": (1040, 40, STD)},
       ["cold heading", "thread rolling", "heat treatment"], "Chassis and driveline bolts."),
    _m("bolt_class_12_9", "Alloy steel bolt, property class 12.9", "Steel", "ISO 898-1", ["fasteners", "engine"],
       {**STEEL, "yield_strength": (1100, 40, STD), "ultimate_strength": (1220, 40, STD)},
       ["cold heading", "thread rolling", "heat treatment"], "Head studs, rod bolts, flywheel bolts. Hydrogen embrittlement risk if plated."),
    # ---------------------------------------------------------------- sheet and structural steels
    _m("hsla_340", "HSLA steel HC340LA", "Steel", "Cold-rolled micro-alloyed sheet (EN 10268)", ["chassis", "body"],
       {**STEEL, "yield_strength": (360, 40, STD), "ultimate_strength": (460, 50, STD)},
       ["stamping", "spot welding"], "Reinforcements and brackets."),
    _m("dp600", "Dual-phase steel DP600", "Steel", "Cold-rolled AHSS sheet", ["chassis", "body"],
       {**STEEL, "yield_strength": (380, 50, STD), "ultimate_strength": (620, 40, STD)},
       ["stamping", "spot welding"], "Crash-relevant panels with good formability."),
    _m("dp980", "Dual-phase steel DP980", "Steel", "Cold-rolled AHSS sheet", ["chassis"],
       {**STEEL, "yield_strength": (650, 80, STD), "ultimate_strength": (1000, 40, STD)},
       ["stamping", "spot welding"], "Sills, cross-members, seat structures."),
    _m("boron_22mnb5_phs", "Press-hardened boron steel 22MnB5", "Steel", "Hot stamped & quenched", ["chassis"],
       {**STEEL, "yield_strength": (1100, 100), "ultimate_strength": (1500, 100)},
       ["hot stamping", "laser cutting"], "B-pillars, roof rails, bumper beams: the safety cage."),
    # ---------------------------------------------------------------- stainless and high-temperature alloys
    _m("ss_304", "Stainless steel 304", "Stainless steel", "Annealed", ["exhaust", "fasteners", "seals"],
       {"density": (8000, 20), "youngs_modulus": (193, 5), "poisson_ratio": (0.29, 0.01), "yield_strength": (215, 30),
        "ultimate_strength": (505, 40), "thermal_conductivity": (16.2, 1), "specific_heat": (500, 15), "cte": (17.3, 0.5),
        "max_service_temp": (870, 30), "solidus_temp": (1400, 20)},
       ["sheet forming", "TIG welding", "tube bending"], "Exhaust tubing, clamps, trim."),
    _m("ss_321", "Stainless steel 321", "Stainless steel", "Annealed", ["exhaust", "turbo"],
       {"density": (8000, 20), "youngs_modulus": (193, 5), "yield_strength": (205, 30), "ultimate_strength": (515, 40),
        "thermal_conductivity": (16.1, 1), "specific_heat": (500, 15), "cte": (16.6, 0.5), "max_service_temp": (900, 30),
        "solidus_temp": (1385, 20)},
       ["tube bending", "TIG welding"], "Titanium-stabilised: manifolds and turbo downpipes that cycle hot."),
    _m("ss_409", "Stainless steel 409", "Stainless steel", "Annealed (ferritic)", ["exhaust"],
       {"density": (7800, 20), "youngs_modulus": (200, 5), "yield_strength": (240, 40), "ultimate_strength": (450, 40),
        "thermal_conductivity": (25, 2), "cte": (11.7, 0.5), "max_service_temp": (815, 30)},
       ["tube bending", "MIG welding"], "Low-cost ferritic grade for mufflers and rear exhaust sections."),
    _m("inconel_625", "Inconel 625", "Nickel alloy", "Annealed", ["exhaust", "turbo"],
       {"density": (8440, 20), "youngs_modulus": (207, 5), "yield_strength": (460, 60), "ultimate_strength": (880, 60),
        "thermal_conductivity": (9.8, 1), "specific_heat": (410, 15), "cte": (12.8, 0.5), "max_service_temp": (980, 30),
        "solidus_temp": (1290, 20)},
       ["tube bending", "TIG welding"], "Thin-wall racing exhaust manifolds and heat shields."),
    _m("inconel_718", "Inconel 718", "Nickel alloy", "Solution treated & aged", ["turbo", "fasteners", "engine"],
       {"density": (8190, 20), "youngs_modulus": (200, 5), "yield_strength": (1035, 70), "ultimate_strength": (1240, 70),
        "thermal_conductivity": (11.4, 1), "specific_heat": (435, 15), "cte": (13.0, 0.5), "max_service_temp": (650, 30),
        "solidus_temp": (1260, 20)},
       ["forging", "CNC machining", "ageing"], "Turbine shafts, exhaust studs, valve springs for extreme duty."),
    _m("inconel_713c", "Inconel 713C", "Nickel alloy", "As cast", ["turbo"],
       {"density": (7910, 30), "youngs_modulus": (200, 8), "yield_strength": (740, 50), "ultimate_strength": (850, 50),
        "max_service_temp": (980, 30), "solidus_temp": (1260, 20)},
       ["investment casting"], "The standard turbocharger turbine-wheel alloy."),
    _m("nimonic_80a", "Nimonic 80A", "Nickel alloy", "Solution treated & aged", ["engine"],
       {"density": (8190, 20), "youngs_modulus": (222, 5), "yield_strength": (780, 60), "ultimate_strength": (1250, 80),
        "thermal_conductivity": (11.2, 1), "cte": (12.7, 0.5), "max_service_temp": (815, 30), "solidus_temp": (1320, 20)},
       ["forging", "friction welding"], "Exhaust valves for turbocharged and racing engines."),
    _m("gamma_tial", "Gamma titanium aluminide (Ti-48Al-2Cr-2Nb)", "Titanium", "Cast & HIPed", ["turbo", "engine"],
       {"density": (3900, 100), "youngs_modulus": (160, 15), "yield_strength": (350, 60), "ultimate_strength": (450, 60),
        "max_service_temp": (750, 50)},
       ["investment casting", "HIP"], "Low-inertia turbine wheels and exhaust valves; brittle at room temperature."),
    # ---------------------------------------------------------------- cast irons
    _m("ductile_iron_65_45_12", "Ductile iron 65-45-12", "Cast iron", "As cast (ASTM A536)", ["engine", "suspension", "transmission"],
       {"density": (7100, 50), "youngs_modulus": (169, 10), "yield_strength": (310, 30, STD), "ultimate_strength": (448, 30, STD),
        "thermal_conductivity": (36, 4), "specific_heat": (506, 20), "cte": (11.0, 0.5), "solidus_temp": (1150, 50)},
       ["casting", "CNC machining"], "Crankshafts for mass-produced engines, knuckles, differential cases."),
    _m("cgi_450", "Compacted graphite iron CGI 450", "Cast iron", "As cast (ISO 16112)", ["engine"],
       {"density": (7100, 50), "youngs_modulus": (145, 10), "yield_strength": (315, 30, STD), "ultimate_strength": (450, 30, STD),
        "thermal_conductivity": (37, 5), "cte": (11.0, 0.5), "solidus_temp": (1150, 50)},
       ["casting", "CNC machining"], "Diesel and high-output petrol cylinder blocks: stiffer than grey iron."),
    _m("grey_iron_high_carbon", "High-carbon grey cast iron", "Cast iron", "Brake-disc grade", ["brakes"],
       {"density": (7100, 80), "youngs_modulus": (100, 15), "ultimate_strength": (190, 30),
        "thermal_conductivity": (55, 8), "specific_heat": (460, 30), "cte": (11.0, 1.0), "solidus_temp": (1150, 50)},
       ["casting", "CNC machining"], "More graphite than standard disc iron: better heat flow and damping, less strength."),
    # ---------------------------------------------------------------- aluminium
    _m("al_6061_t6", "Aluminium 6061", "Aluminium", "T6", ["suspension", "chassis", "wheels", "electrical"],
       {"density": (2700, 10), "youngs_modulus": (68.9, 1.5), "poisson_ratio": (0.33, 0.01), "yield_strength": (276, 20),
        "ultimate_strength": (310, 20), "fatigue_strength": (96.5, 15, HANDBOOK + "; 5e8 cycles, R.R. Moore"),
        "thermal_conductivity": (167, 5), "specific_heat": (896, 20), "cte": (23.6, 0.5), "solidus_temp": (582, 5)},
       ["extrusion", "forging", "CNC machining", "TIG welding"], "Brackets, billet parts, battery trays."),
    _m("al_6082_t6", "Aluminium 6082", "Aluminium", "T6", ["suspension", "chassis"],
       {"density": (2700, 10), "youngs_modulus": (70, 1.5), "yield_strength": (260, 20), "ultimate_strength": (310, 20),
        "thermal_conductivity": (170, 6), "cte": (23.1, 0.5), "solidus_temp": (575, 5)},
       ["extrusion", "forging"], "Forged control arms and extruded crash structures."),
    _m("al_2024_t3", "Aluminium 2024", "Aluminium", "T3", ["suspension", "fasteners"],
       {"density": (2780, 10), "youngs_modulus": (73.1, 1.5), "yield_strength": (345, 20), "ultimate_strength": (483, 20),
        "fatigue_strength": (138, 15, HANDBOOK + "; 5e8 cycles"), "thermal_conductivity": (121, 5), "cte": (23.2, 0.5),
        "solidus_temp": (502, 5)},
       ["CNC machining", "riveting"], "High fatigue strength; poor corrosion resistance unless clad."),
    _m("al_a356_t6", "Aluminium A356", "Aluminium", "T6 casting", ["wheels", "engine", "suspension"],
       {"density": (2670, 10), "youngs_modulus": (72.4, 2), "yield_strength": (180, 25), "ultimate_strength": (250, 25),
        "thermal_conductivity": (151, 6), "specific_heat": (963, 20), "cte": (21.5, 0.5), "solidus_temp": (555, 5)},
       ["low-pressure casting", "CNC machining"], "Cast wheels, cylinder heads, knuckles."),
    _m("al_4032_t6", "Aluminium 4032", "Aluminium", "T6", ["engine"],
       {"density": (2680, 10), "youngs_modulus": (79, 2), "yield_strength": (315, 25), "ultimate_strength": (380, 25),
        "thermal_conductivity": (155, 6), "cte": (19.4, 0.5), "solidus_temp": (532, 5)},
       ["forging", "CNC machining"], "High-silicon forged-piston alloy: lower expansion than 2618 for tighter clearances."),
    _m("al_5182_o", "Aluminium 5182", "Aluminium", "O temper sheet", ["body"],
       {"density": (2650, 10), "youngs_modulus": (70, 2), "yield_strength": (130, 20), "ultimate_strength": (275, 20)},
       ["stamping", "riveting", "adhesive bonding"], "Inner panels and closures."),
    _m("al_mmc_sic", "Aluminium MMC (A359 + 20 % SiC)", "Aluminium", "Cast metal-matrix composite", ["brakes"],
       {"density": (2770, 30), "youngs_modulus": (100, 10), "ultimate_strength": (330, 40), "thermal_conductivity": (160, 20),
        "specific_heat": (840, 40), "cte": (17.5, 1.0), "max_service_temp": (450, 40)},
       ["casting", "diamond machining"], "Light brake discs and drums; keep the friction surface well below ~450 °C."),
    # ---------------------------------------------------------------- magnesium and titanium
    _m("mg_az91d", "Magnesium AZ91D", "Magnesium", "Die cast", ["transmission", "interior", "engine"],
       {"density": (1810, 10), "youngs_modulus": (45, 2), "yield_strength": (160, 20), "ultimate_strength": (230, 20),
        "thermal_conductivity": (72, 5), "cte": (26, 1), "solidus_temp": (470, 10)},
       ["high-pressure die casting"], "Gearbox cases, cam covers, steering-wheel frames."),
    _m("mg_am60b", "Magnesium AM60B", "Magnesium", "Die cast", ["wheels", "interior", "chassis"],
       {"density": (1800, 10), "youngs_modulus": (45, 2), "yield_strength": (130, 15), "ultimate_strength": (220, 20),
        "thermal_conductivity": (61, 5), "cte": (25.6, 1), "solidus_temp": (540, 10)},
       ["high-pressure die casting"], "Ductile grade for instrument-panel beams, seat frames and wheels."),
    _m("ti_grade_2", "Titanium Grade 2 (CP)", "Titanium", "Annealed", ["exhaust", "fasteners"],
       {"density": (4510, 20), "youngs_modulus": (105, 3), "yield_strength": (340, 60), "ultimate_strength": (450, 60),
        "thermal_conductivity": (16.4, 1), "specific_heat": (523, 15), "cte": (8.6, 0.4), "max_service_temp": (400, 40),
        "solidus_temp": (1665, 20)},
       ["tube bending", "TIG welding (inert shielding)"], "Lightweight exhaust systems."),
    _m("ti_beta_c", "Titanium Beta-C (Ti-3Al-8V-6Cr-4Mo-4Zr)", "Titanium", "Solution treated & aged", ["suspension", "engine", "fasteners"],
       {"density": (4820, 20), "youngs_modulus": (103, 4), "yield_strength": (1100, 100), "ultimate_strength": (1200, 100)},
       ["wire drawing", "coiling", "ageing"], "Lightweight suspension and valve springs."),
    # ---------------------------------------------------------------- copper alloys
    _m("copper_c11000", "Copper C11000 (ETP)", "Copper", "Annealed", ["electrical"],
       {"density": (8940, 20), "youngs_modulus": (117, 3), "yield_strength": (69, 20), "ultimate_strength": (220, 20),
        "thermal_conductivity": (388, 10), "specific_heat": (385, 10), "cte": (17.0, 0.5), "solidus_temp": (1065, 10)},
       ["drawing", "stamping"], "Bus bars, motor windings, cables."),
    _m("al_bronze_c95400", "Aluminium bronze C95400", "Copper", "As cast", ["transmission", "bearings", "engine"],
       {"density": (7450, 20), "youngs_modulus": (107, 4), "yield_strength": (241, 30), "ultimate_strength": (586, 40),
        "thermal_conductivity": (58.7, 4), "cte": (16.2, 0.5)},
       ["casting", "CNC machining"], "Synchroniser rings, bushings, valve guides."),
    # ---------------------------------------------------------------- composites
    _m("cfrp_qi", "Carbon fibre / epoxy, quasi-isotropic", "Composite", "Standard-modulus fibre, [0/±45/90] layup",
       ["body", "chassis", "interior", "suspension"],
       {"density": (1550, 50), "youngs_modulus": (50, 8), "ultimate_strength": (550, 100), "cte": (2.0, 2.0),
        "max_service_temp": (120, 20, HANDBOOK + "; limited by the epoxy glass transition")},
       ["prepreg layup", "autoclave", "RTM"], "In-plane values; through-thickness strength is far lower. Brittle: no yield."),
    _m("cfrp_ud", "Carbon fibre / epoxy, unidirectional", "Composite", "Along the fibres", ["chassis", "suspension", "transmission"],
       {"density": (1550, 50), "youngs_modulus": (135, 10), "ultimate_strength": (2400, 250),
        "max_service_temp": (120, 20, HANDBOOK + "; limited by the epoxy glass transition")},
       ["prepreg layup", "filament winding", "pultrusion"], "Fibre direction only: propshafts, wishbones, springs."),
    _m("gfrp_qi", "Glass fibre / epoxy, quasi-isotropic", "Composite", "E-glass, [0/±45/90] layup", ["body", "interior", "electrical"],
       {"density": (1900, 60), "youngs_modulus": (20, 4), "ultimate_strength": (300, 60), "max_service_temp": (120, 20)},
       ["hand layup", "RTM", "SMC compression moulding"], "Body panels and leaf springs at lower cost than carbon."),
    # ---------------------------------------------------------------- polymers and elastomers
    _m("pa66_gf30", "Polyamide 66, 30 % glass", "Polymer", "Dry as moulded", ["engine", "turbo", "electrical"],
       {"density": (1360, 20), "youngs_modulus": (9.5, 1.0), "ultimate_strength": (185, 20), "cte": (30, 10),
        "max_service_temp": (150, 20, SUPPLIER)},
       ["injection moulding"], "Intake manifolds, engine covers, radiator end tanks. Stiffness drops ~30 % when moisture-conditioned."),
    _m("peek", "PEEK", "Polymer", "Unfilled", ["transmission", "seals", "engine"],
       {"density": (1300, 20), "youngs_modulus": (3.6, 0.3), "yield_strength": (100, 10), "ultimate_strength": (100, 10),
        "thermal_conductivity": (0.25, 0.05), "max_service_temp": (250, 10, SUPPLIER)},
       ["injection moulding", "CNC machining"], "Thrust washers, seal rings, pump parts."),
    _m("pp_talc20", "Polypropylene, 20 % talc", "Polymer", "Injection grade", ["interior", "body"],
       {"density": (1050, 20), "youngs_modulus": (2.0, 0.4), "ultimate_strength": (30, 5), "max_service_temp": (100, 10, SUPPLIER)},
       ["injection moulding"], "Bumper fascias, door trims, dashboards."),
    _m("abs", "ABS", "Polymer", "General purpose", ["interior"],
       {"density": (1050, 20), "youngs_modulus": (2.3, 0.3), "ultimate_strength": (40, 5), "max_service_temp": (80, 10, SUPPLIER)},
       ["injection moulding"], "Trim, consoles, grilles."),
    _m("polycarbonate", "Polycarbonate", "Polymer", "UV-stabilised, hard-coated", ["glazing", "interior"],
       {"density": (1200, 10), "youngs_modulus": (2.35, 0.1), "yield_strength": (62, 5), "max_service_temp": (125, 10, SUPPLIER)},
       ["injection moulding"], "Headlamp lenses and lightweight side or rear windows."),
    _m("glass_laminated", "Laminated soda-lime glass", "Glass", "Windscreen laminate (glass/PVB/glass)", ["glazing"],
       {"density": (2500, 20), "youngs_modulus": (72, 2), "ultimate_strength": (45, 15, HANDBOOK + "; design strength, flaw-dependent"),
        "thermal_conductivity": (1.0, 0.1), "cte": (9.0, 0.5)},
       ["float glass", "lamination", "bending"], "Brittle: strength depends on surface flaws and edge finish."),
    _m("natural_rubber", "Natural rubber", "Elastomer", "Filled, vulcanised", ["suspension", "wheels"],
       {"density": (930, 30), "ultimate_strength": (25, 5, SUPPLIER), "max_service_temp": (80, 10, SUPPLIER)},
       ["moulding", "vulcanising"], "Suspension bushings, engine mounts, tyre compounds."),
    _m("epdm", "EPDM rubber", "Elastomer", "Peroxide cured", ["seals", "engine", "body"],
       {"density": (1150, 150), "ultimate_strength": (15, 5, SUPPLIER), "max_service_temp": (150, 10, SUPPLIER)},
       ["extrusion", "moulding"], "Coolant hoses, door and window seals. Not oil resistant."),
    _m("nbr", "Nitrile rubber (NBR)", "Elastomer", "Sulphur cured", ["seals", "engine"],
       {"density": (1300, 100), "ultimate_strength": (15, 5, SUPPLIER), "max_service_temp": (120, 10, SUPPLIER)},
       ["moulding"], "Fuel and oil seals, O-rings."),
    _m("fkm", "Fluoroelastomer (FKM)", "Elastomer", "Bisphenol cured", ["seals", "turbo", "engine"],
       {"density": (1850, 100), "ultimate_strength": (12, 4, SUPPLIER), "max_service_temp": (205, 10, SUPPLIER)},
       ["moulding"], "High-temperature seals: turbo oil lines, crank seals, fuel injectors."),
    # ---------------------------------------------------------------- friction materials and brake discs
    _m("pad_nao", "Brake pad, organic (NAO)", "Friction material", "Street compound", ["brakes"],
       {"density": (2000, 300, SUPPLIER), "friction_coefficient": (0.40, 0.05, SUPPLIER),
        "thermal_conductivity": (1.0, 0.5, SUPPLIER), "max_service_temp": (350, 50, SUPPLIER)},
       ["compression moulding"], "Quiet and low-dust; fades early under repeated hard stops."),
    _m("pad_semimetallic", "Brake pad, semi-metallic", "Friction material", "Street / fast-road compound", ["brakes"],
       {"density": (2600, 300, SUPPLIER), "friction_coefficient": (0.42, 0.05, SUPPLIER),
        "thermal_conductivity": (3.0, 1.5, SUPPLIER), "max_service_temp": (500, 50, SUPPLIER)},
       ["compression moulding"], "Steel-fibre compound: good fade resistance, more noise and disc wear."),
    _m("pad_ceramic", "Brake pad, low-metallic ceramic", "Friction material", "Street compound", ["brakes"],
       {"density": (2400, 300, SUPPLIER), "friction_coefficient": (0.38, 0.05, SUPPLIER),
        "max_service_temp": (550, 60, SUPPLIER)},
       ["compression moulding"], "Clean and quiet with stable friction; less bite when cold."),
    _m("pad_sintered_race", "Brake pad, sintered racing", "Friction material", "Track compound", ["brakes"],
       {"density": (4500, 600, SUPPLIER), "friction_coefficient": (0.50, 0.06, SUPPLIER),
        "max_service_temp": (750, 80, SUPPLIER)},
       ["sintering"], "High and stable friction when hot; poor when cold, hard on discs."),
    _m("carbon_ceramic_csic", "Carbon-ceramic (C/SiC)", "Ceramic composite", "Brake-disc grade", ["brakes"],
       {"density": (2450, 150), "thermal_conductivity": (30, 15), "specific_heat": (800, 150), "cte": (2.5, 1.0),
        "max_service_temp": (1000, 100, SUPPLIER + "; oxidation of the carbon fibres limits life above this")},
       ["CVI / liquid silicon infiltration", "diamond grinding"], "About half the mass of an iron disc; very fade resistant."),
    _m("carbon_carbon", "Carbon-carbon (C/C)", "Ceramic composite", "Racing brake grade", ["brakes", "transmission"],
       {"density": (1800, 100), "thermal_conductivity": (50, 25), "specific_heat": (900, 200),
        "max_service_temp": (1100, 150, SUPPLIER + "; needs high temperature to grip and oxidises in long use")},
       ["CVD densification", "CNC machining"], "Formula-car brakes and multi-plate racing clutches."),
    _m("clutch_organic", "Clutch facing, organic", "Friction material", "Woven / moulded", ["transmission"],
       {"density": (2000, 300, SUPPLIER), "friction_coefficient": (0.35, 0.05, SUPPLIER), "max_service_temp": (300, 40, SUPPLIER)},
       ["moulding", "riveting"], "Smooth engagement for road cars."),
    _m("clutch_cerametallic", "Clutch facing, cerametallic", "Friction material", "Sintered buttons", ["transmission"],
       {"density": (4500, 600, SUPPLIER), "friction_coefficient": (0.45, 0.06, SUPPLIER), "max_service_temp": (500, 60, SUPPLIER)},
       ["sintering"], "Higher torque capacity and heat tolerance; harsher engagement."),
]
